### ISSUE TITLE
RequireJS Optimization

### ISSUE THREAD

**Issue by orielz** [marcorinck/ngStart#21]
Hi, thanks for great project!

I have problem with optimization.

When I try to build a version with the "grunt install" command,
I get an output to the “target” folder and it looked fine,
But then, I`m trying to run local web server with Visual studio and run the index.html I’m getting the following error:

Uncaught ReferenceError: minErr is not defined 

from angular.js script line 144

How do i solve it?

Thanks!

**Comment by marcorinck** [comment]
Yes, there seems to be a problem with optimization during build. At first glance I can't find the cause. I'll look into it,

**Comment by marcorinck** [comment]
all build problems are fixed now
