### ISSUE TITLE
Check/Update Deps

### ISSUE THREAD

**Issue by robinboehm** [marcorinck/ngStart#26]
https://gemnasium.com/marcorinck/ngStart

or

https://david-dm.org/marcorinck/ngStart#info=devDependencies

I prefer to use david, because they create an alert earlier! ;)

**Comment by marcorinck** [comment]
yeah, I merged your PR. Have to look into that soon ... :-)

**Comment by robinboehm** [comment]
:+1:

**Comment by marcorinck** [comment]
updated all deps and used libraries to current versions

**Comment by robinboehm** [comment]
Last but not least :D

Send from mobile
