### ISSUE TITLE
production deployment error

### ISSUE THREAD

**Issue by TrangNguyen** [marcorinck/ngStart#28]
Hi,
could you please give more information on production deployment please. While the app works very well on localhost, I've uploaded the target folder (generated by grunt install) to a ftp server. However it doesn't work. One can see the navbar but no content. Chrome:
Uncaught object 
Uncaught TypeError: undefined is not a function
Firefox and Safari:
Error: [$injector:modulerr] http://errors.angularjs.org/undefined/$injector/modulerr?
And wouldn't it make sense to link scripts such as angular.min.js from google cdn instead of concat it in production?
![screen shot 2014-07-09 at 18 43 25](https://cloud.githubusercontent.com/assets/2684809/3527758/3a055208-0788-11e4-825f-2afa807a9c9e.png)

Obviously I'm doing something wrong. Tips, advice and help very much appreciated.
Trang

**Comment by marcorinck** [comment]
There were (at least) 2 problems with production deployment version:
- ng-app attribute was used on html tag despite that manual angular bootstrapping is used
- angular-translate and its dependencies was not included in generated main.js by requireJS. Apparently requirejs had a problem with building the dependency tree and didn't pick up the translate module to include in main.js file. I changed the configuration and removed a feature that was not used in this project anyway (config.standardRequireModules) as it was a relict of an internal project of mine.

I will push a fix in a few minutes.
