### ISSUE TITLE
Update folder structure

### ISSUE THREAD

**Issue by marcorinck** [marcorinck/ngStart#5]
Currently the folder structure is similar to a (java) maven project. 

Update the folder structure so that its more like "normal" web projects, so that folders under _src/main/_ are put into the root folder. 

To be discussed: project files in project root (like package.json) should NOT be conflicting with _real_ project files.

**Comment by BarrySkidmore** [comment]
You may like what we have done with our fork, I updated it here, I do not believe you would be interested in the massive puller request that changes the core more or less completely...

https://github.com/alertlogic/ngStart/

**Comment by marcorinck** [comment]
removed maven like folder structure, project now uses "app" for the application and "test" for all tests
