### ISSUE TITLE
no hardcoded css file list

### ISSUE THREAD

**Issue by marcorinck** [marcorinck/ngStart#6]
Currently all css files used by the project need to be added manually in gruntfile.js to the cssmin.css task configuration in the correct order. 

Make that more practical, at least as a config in package.json. Maybe there could be another even more automatic solution (order of css files is important!)

**Comment by BarrySkidmore** [comment]
Might I suggest that you use LESS to compile all .less files (using expand true mapping) into a single main CSS file, then cssmin that single file in the build process.

**Comment by marcorinck** [comment]
included LESS compiler as suggested
